### ISSUE TITLE
The value of min(c) in "Tutorial_ hash_center_generation.ipynb"

### ISSUE THREAD

**Issue by CristinaUSC** [yuanli2333/Hadamard-Matrix-for-hashing#1]
Hi,

You set the value min(c)=20 for ImageNet in '.ipynb' file.
How to set the value of min(c) for other datasets, such as COCO or NUS_WIDE?

**Comment by yuanli2333** [comment]
The min(c) is an empirical value. In our experiments, we choose min(c) in the range of K/4 to K/3. Actually, we found that our method is robust with this value.

**Comment by yuanli2333** [comment]
> Hi,
> 
> You set the value min(c)=20 for ImageNet in '.ipynb' file.
> How to set the value of min(c) for other datasets, such as COCO or NUS_WIDE?

The min(c) is an empirical value. In our experiments, we choose min(c) in the range of K/4 to K/3. Actually, we found that our method is robust with this value.
