### ISSUE TITLE
I'm sorry to disturb you. Can you provide the supplementary materials mentioned in the paper?

### ISSUE THREAD

**Issue by Liquor520** [yuanli2333/Hadamard-Matrix-for-hashing#11]

**Comment by githubsghww** [comment]
同求

**Comment by yuanli2333** [comment]
https://openaccess.thecvf.com/content_CVPR_2020/html/Yuan_Central_Similarity_Quantization_for_Efficient_Image_and_Video_Retrieval_CVPR_2020_paper.html
The 'supp' is the supplementary materials.
