### ISSUE TITLE
Video Hashing

### ISSUE THREAD

**Issue by silencelzx** [yuanli2333/Hadamard-Matrix-for-hashing#13]
Thanks for the great work!
I 'm interested in your video hashing work.  Can you release your video hashing code?
My email is imbachenyukun@sina.cn. Hope to communicate with me.

**Comment by yuanli2333** [comment]
I plan to release video hashing codes in this weekend.

**Comment by yuanli2333** [comment]
Video hashing: [here](https://github.com/yuanli2333/Hadamard-Matrix-for-hashing/tree/master/video)
