### ISSUE TITLE
Can you share the results based on AlexNet?

### ISSUE THREAD

**Issue by chenshen03** [yuanli2333/Hadamard-Matrix-for-hashing#2]
Most deep hashing methods adopt AlexNet as the backbone. For a fair comparison, can you share the results of this method under AlexNet?

**Comment by yuanli2333** [comment]
(1). For fair comparison, the four deep methods use the same feature learning network in our paper. 
(2). I will share the results by adopting AlexNet as backbone after these busy period.

**Comment by yuanli2333** [comment]
> Most deep hashing methods adopt AlexNet as the backbone. For a fair comparison, can you share the results of this method under AlexNet?

**Comment by yuanli2333** [comment]
> > Most deep hashing methods adopt AlexNet as the backbone. For a fair comparison, can you share the results of this method under AlexNet?

(1). For fair comparison, the four deep methods use the same feature learning network in our paper.
(2). I will share the results by adopting AlexNet as backbone after these busy period.

**Comment by zwzhang123** [comment]
Could you share the results on NUS-WIDE dataset using AlexNet?
