### ISSUE TITLE
Video hashing

### ISSUE THREAD

**Issue by KasparPeterson** [yuanli2333/Hadamard-Matrix-for-hashing#3]
Thanks for the great work!

Super excited to play around with video hashing. Are there any plans for releasing the video code and configurations?

**Comment by yuanli2333** [comment]
> Thanks for the great work!
> 
> Super excited to play around with video hashing. Are there any plans for releasing the video code and configurations?

I will release codes for video hashing after this busy period.

**Comment by justfitting** [comment]
> > Thanks for the great work!
> > Super excited to play around with video hashing. Are there any plans for releasing the video code and configurations?
> 
> I will release codes for video hashing after this busy period.
great work! when will you  release the video code and configurations?

**Comment by Usernamezhx** [comment]
> > Thanks for the great work!
> > Super excited to play around with video hashing. Are there any plans for releasing the video code and configurations?
> 
> I will release codes for video hashing after this busy period.

**Comment by yuanli2333** [comment]
Video hashing: [here](https://github.com/yuanli2333/Hadamard-Matrix-for-hashing/tree/master/video)
