### ISSUE TITLE
pairwise loss

### ISSUE THREAD

**Issue by hbellafkir** [yuanli2333/Hadamard-Matrix-for-hashing#8]
hi,

The paper doesn't use any pairwise loss. Is this a joke? why are you implementing something different that the paper's claim?

thanks in advance

**Comment by hbellafkir** [comment]
Ok lambda1 is set to be 0, which weights the pairwise loss. I was very upset before cause its not the first time, that I read a paper, but the code itself tells another story.

**Comment by Kenny-Li2023** [comment]
> Ok lambda1 is set to be 0, which weights the pairwise loss. I was very upset before cause its not the first time, that I read a paper, but the code itself tells another story.

Do you know why the author uses pairwise loss?

**Comment by hbellafkir** [comment]
They set lambda1 to be 0 for Training, so they doesn't use pairwise loss.

**Comment by Kenny-Li2023** [comment]
> They set lambda1 to be 0 for Training, so they doesn't use pairwise loss.

Why is Q_loss completely different from LQ in the paper？
